# Generated by Django 4.2.14 on 2026-08-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('parcela', models.CharField(max_length=100, verbose_name='Parcela')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
            ],
        ),
    ]
