# Generated by Django 4.2.14 on 2026-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
