# Generated by Django 4.2.14 on 2026-08-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_documento_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='numero_contrato',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Contrato'),
        ),
    ]
