# Generated by Django 4.2.14 on 2026-08-22 03:22

import django.core.validators
from django.db import migrations, models
import gestor.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_documento_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf']), gestor.models.validar_tamano_archivo], verbose_name='Archivo'),
        ),
    ]
